// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: color remote

#ifndef UI_APP_SCREEN_H
#define UI_APP_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_app_screen
extern void ui_app_screen_screen_init(void);
extern void ui_app_screen_screen_destroy(void);
extern lv_obj_t * ui_app_screen;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label1;
extern void ui_event_Colorwheel2(lv_event_t * e);
extern lv_obj_t * ui_Colorwheel2;
extern lv_obj_t * ui_Label2;
extern void ui_event_transitionTime(lv_event_t * e);
extern lv_obj_t * ui_transitionTime;
extern lv_obj_t * ui_Label3;
extern void ui_event_Red(lv_event_t * e);
extern lv_obj_t * ui_Red;
extern lv_obj_t * ui_Label4;
extern void ui_event_Green(lv_event_t * e);
extern lv_obj_t * ui_Green;
extern lv_obj_t * ui_Label5;
extern void ui_event_Blue(lv_event_t * e);
extern lv_obj_t * ui_Blue;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Bar1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

