// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: color remote

#ifndef UI_LOADING_SCREEN_H
#define UI_LOADING_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_loading_screen
extern void ui_loading_screen_screen_init(void);
extern void ui_loading_screen_screen_destroy(void);
extern lv_obj_t * ui_loading_screen;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

